pipeline {
    agent any

    parameters {
         string(name: 'tomcat_dev', defaultValue: 'koko-01.mykezy.com', description: 'Staging Server')
         string(name: 'tomcat_prod', defaultValue: 'koko-01.mykezy.com', description: 'Production Server')
    }

    triggers {
         pollSCM('* * * * *')
     }

stages{
        stage('Build'){
            steps {
                sh '/apache-maven-3.5.2/bin/mvn clean package'
            }
            post {
                success {
                    echo 'Now Archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }

        stage ('Deployments'){
            parallel{
                stage ('Deploy to Staging'){
                    sshagent (credentials: ['ec2-user']) {
                       step {
                        sh "scp -o StrictHostKeyChecking=no -i **/target/*.war ec2-user@${params.tomcat_dev}:/home/ec2-user/apache-tomcat7-stage/webapps"
                    }
                  }
                }

                stage ("Deploy to Production"){
                    steps {
                        sh "scp -o StrictHostKeyChecking=no -i /var/jenkins_home/.ssh_keys/inno-oke-key.pem **/target/*.war ec2-user@${params.tomcat_prod}:/home/ec2-user/apache-tomcat-7.0.82/webapps"
                    }
                }
            }
        }
    }
}
