pipeline {
    agent {
      label 'tomcat-user'
     }

    parameters {
         string(name: 'tomcat_dev', defaultValue: 'koko-01.mykezy.com', description: 'Staging Server')
         string(name: 'tomcat_prod', defaultValue: 'koko-01.mykezy.com', description: 'Production Server')
    }

    triggers {
         pollSCM('* * * * *')
     }

stages{
        stage('Build'){
            steps {
                sh '/apache-maven-3.5.2/bin/mvn clean package'
            }
            post {
                success {
                    echo 'Now Archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }

        stage ('Deployments'){
            parallel{
                stage ('Deploy to Staging'){
                   steps {
                      sshagent (credentials: ['oke-key']) {
                        sh "scp -o StrictHostKeyChecking=no **/target/*.war ec2-user@${params.tomcat_dev}:/home/ec2-user/apache-tomcat7-stage/webapps"
                    }
                  }
                }

                stage ("Deploy to Production"){
                    steps {
                       sshagent (credentials: ['oke-key']) {
                        sh "scp -o StrictHostKeyChecking=no  **/target/*.war ec2-user@${params.tomcat_prod}:/home/ec2-user/apache-tomcat-7.0.82/webapps"
                    }
                 }
               }
            }
        }
    }
}
